server:
  port: 8080

spring:
  application:
    name: spring-file-watch
  profiles:
    active: dev
task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50
