server:
  port: 8080

spring:
  application:
    name: spring-yml-include
  profiles:
    active: dev
task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50
logging:
  level: info