server:
  port: 8080

spring:
  application:
    name: spring-websocket
  profiles:
    active: dev
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**