server:
  port: 8080
spring:
  application:
    name: spring-websocket
  profiles:
    active: dev
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
# 这里配置了一个端口，其实还有很多的配置
tio:
  websocket:
    server:
      port: 8989
socketio:
  websocket:
    host: localhost
    port: 9092
    # ssl配置
    #keyStore:
    #  password: test1234
    #  filePath: ssl/keystore.jks
    # 连接数大小
    workCount: 100
    # 允许客户请求
    allowCustomRequests: true
    # 协议升级超时时间(毫秒)，默认10秒，HTTP握手升级为ws协议超时时间
    upgradeTimeout: 10000
    # Ping消息超时时间(毫秒)，默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 60000
    # Ping消息间隔(毫秒)，默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000
    # 设置HTTP交互最大内容长度
    maxHttpContentLength: 1048576
    # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576
