server:
  port: 8080

spring:
  application:
    name: spring-grpc-consumer
  profiles:
    active: dev
auth.username: user
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:50055'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext