// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/UbixUser.proto
// Protobuf Java Version: 4.28.2

package com.atguigu.springcloud.other.proto;

public final class UbixUserModel {
  private UbixUserModel() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      UbixUserModel.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UbixUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UbixUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>int32 gender = 2;</code>
     * @return The gender.
     */
    int getGender();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>repeated string keywords = 4;</code>
     * @return A list containing the keywords.
     */
    java.util.List<java.lang.String>
        getKeywordsList();
    /**
     * <code>repeated string keywords = 4;</code>
     * @return The count of keywords.
     */
    int getKeywordsCount();
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    java.lang.String getKeywords(int index);
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    com.google.protobuf.ByteString
        getKeywordsBytes(int index);

    /**
     * <code>string ext = 5;</code>
     * @return The ext.
     */
    java.lang.String getExt();
    /**
     * <code>string ext = 5;</code>
     * @return The bytes for ext.
     */
    com.google.protobuf.ByteString
        getExtBytes();

    /**
     * <code>repeated string tags = 6;</code>
     * @return A list containing the tags.
     */
    java.util.List<java.lang.String>
        getTagsList();
    /**
     * <code>repeated string tags = 6;</code>
     * @return The count of tags.
     */
    int getTagsCount();
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    java.lang.String getTags(int index);
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);

    /**
     * <code>repeated string category = 7;</code>
     * @return A list containing the category.
     */
    java.util.List<java.lang.String>
        getCategoryList();
    /**
     * <code>repeated string category = 7;</code>
     * @return The count of category.
     */
    int getCategoryCount();
    /**
     * <code>repeated string category = 7;</code>
     * @param index The index of the element to return.
     * @return The category at the given index.
     */
    java.lang.String getCategory(int index);
    /**
     * <code>repeated string category = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the category at the given index.
     */
    com.google.protobuf.ByteString
        getCategoryBytes(int index);

    /**
     * <code>repeated string installed_apps = 8;</code>
     * @return A list containing the installedApps.
     */
    java.util.List<java.lang.String>
        getInstalledAppsList();
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @return The count of installedApps.
     */
    int getInstalledAppsCount();
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @param index The index of the element to return.
     * @return The installedApps at the given index.
     */
    java.lang.String getInstalledApps(int index);
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the installedApps at the given index.
     */
    com.google.protobuf.ByteString
        getInstalledAppsBytes(int index);
  }
  /**
   * Protobuf type {@code UbixUser}
   */
  public static final class UbixUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UbixUser)
      UbixUserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        UbixUser.class.getName());
    }
    // Use UbixUser.newBuilder() to construct.
    private UbixUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UbixUser() {
      uid_ = "";
      keywords_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      ext_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      category_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      installedApps_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.atguigu.springcloud.other.proto.UbixUserModel.internal_static_UbixUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.atguigu.springcloud.other.proto.UbixUserModel.internal_static_UbixUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.class, com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uid_ = "";
    /**
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 2;
    private int gender_ = 0;
    /**
     * <code>int32 gender = 2;</code>
     * @return The gender.
     */
    @java.lang.Override
    public int getGender() {
      return gender_;
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_ = 0;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int KEYWORDS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string keywords = 4;</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      return keywords_;
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public java.lang.String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated string keywords = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }

    public static final int EXT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ext_ = "";
    /**
     * <code>string ext = 5;</code>
     * @return The ext.
     */
    @java.lang.Override
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      }
    }
    /**
     * <code>string ext = 5;</code>
     * @return The bytes for ext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string tags = 6;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    public static final int CATEGORY_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList category_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string category = 7;</code>
     * @return A list containing the category.
     */
    public com.google.protobuf.ProtocolStringList
        getCategoryList() {
      return category_;
    }
    /**
     * <code>repeated string category = 7;</code>
     * @return The count of category.
     */
    public int getCategoryCount() {
      return category_.size();
    }
    /**
     * <code>repeated string category = 7;</code>
     * @param index The index of the element to return.
     * @return The category at the given index.
     */
    public java.lang.String getCategory(int index) {
      return category_.get(index);
    }
    /**
     * <code>repeated string category = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the category at the given index.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes(int index) {
      return category_.getByteString(index);
    }

    public static final int INSTALLED_APPS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList installedApps_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @return A list containing the installedApps.
     */
    public com.google.protobuf.ProtocolStringList
        getInstalledAppsList() {
      return installedApps_;
    }
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @return The count of installedApps.
     */
    public int getInstalledAppsCount() {
      return installedApps_.size();
    }
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @param index The index of the element to return.
     * @return The installedApps at the given index.
     */
    public java.lang.String getInstalledApps(int index) {
      return installedApps_.get(index);
    }
    /**
     * <code>repeated string installed_apps = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the installedApps at the given index.
     */
    public com.google.protobuf.ByteString
        getInstalledAppsBytes(int index) {
      return installedApps_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
      }
      if (gender_ != 0) {
        output.writeInt32(2, gender_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < keywords_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, keywords_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, ext_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, tags_.getRaw(i));
      }
      for (int i = 0; i < category_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, category_.getRaw(i));
      }
      for (int i = 0; i < installedApps_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, installedApps_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
      }
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gender_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keywords_.size(); i++) {
          dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeywordsList().size();
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, ext_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += computeStringSizeNoTag(tags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < category_.size(); i++) {
          dataSize += computeStringSizeNoTag(category_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCategoryList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < installedApps_.size(); i++) {
          dataSize += computeStringSizeNoTag(installedApps_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInstalledAppsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser)) {
        return super.equals(obj);
      }
      com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser other = (com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (getGender()
          != other.getGender()) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getKeywordsList()
          .equals(other.getKeywordsList())) return false;
      if (!getExt()
          .equals(other.getExt())) return false;
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!getCategoryList()
          .equals(other.getCategoryList())) return false;
      if (!getInstalledAppsList()
          .equals(other.getInstalledAppsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getKeywordsCount() > 0) {
        hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getKeywordsList().hashCode();
      }
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + getExt().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      if (getCategoryCount() > 0) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getCategoryList().hashCode();
      }
      if (getInstalledAppsCount() > 0) {
        hash = (37 * hash) + INSTALLED_APPS_FIELD_NUMBER;
        hash = (53 * hash) + getInstalledAppsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UbixUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UbixUser)
        com.atguigu.springcloud.other.proto.UbixUserModel.UbixUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.atguigu.springcloud.other.proto.UbixUserModel.internal_static_UbixUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.atguigu.springcloud.other.proto.UbixUserModel.internal_static_UbixUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.class, com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.Builder.class);
      }

      // Construct using com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uid_ = "";
        gender_ = 0;
        age_ = 0;
        keywords_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        ext_ = "";
        tags_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        category_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        installedApps_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.atguigu.springcloud.other.proto.UbixUserModel.internal_static_UbixUser_descriptor;
      }

      @java.lang.Override
      public com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser getDefaultInstanceForType() {
        return com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.getDefaultInstance();
      }

      @java.lang.Override
      public com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser build() {
        com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser buildPartial() {
        com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser result = new com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uid_ = uid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          keywords_.makeImmutable();
          result.keywords_ = keywords_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.ext_ = ext_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          tags_.makeImmutable();
          result.tags_ = tags_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          category_.makeImmutable();
          result.category_ = category_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          installedApps_.makeImmutable();
          result.installedApps_ = installedApps_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser) {
          return mergeFrom((com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser other) {
        if (other == com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.keywords_.isEmpty()) {
          if (keywords_.isEmpty()) {
            keywords_ = other.keywords_;
            bitField0_ |= 0x00000008;
          } else {
            ensureKeywordsIsMutable();
            keywords_.addAll(other.keywords_);
          }
          onChanged();
        }
        if (!other.getExt().isEmpty()) {
          ext_ = other.ext_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ |= 0x00000020;
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (!other.category_.isEmpty()) {
          if (category_.isEmpty()) {
            category_ = other.category_;
            bitField0_ |= 0x00000040;
          } else {
            ensureCategoryIsMutable();
            category_.addAll(other.category_);
          }
          onChanged();
        }
        if (!other.installedApps_.isEmpty()) {
          if (installedApps_.isEmpty()) {
            installedApps_ = other.installedApps_;
            bitField0_ |= 0x00000080;
          } else {
            ensureInstalledAppsIsMutable();
            installedApps_.addAll(other.installedApps_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                gender_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureKeywordsIsMutable();
                keywords_.add(s);
                break;
              } // case 34
              case 42: {
                ext_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureTagsIsMutable();
                tags_.add(s);
                break;
              } // case 50
              case 58: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCategoryIsMutable();
                category_.add(s);
                break;
              } // case 58
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureInstalledAppsIsMutable();
                installedApps_.add(s);
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        uid_ = getDefaultInstance().getUid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <code>int32 gender = 2;</code>
       * @return The gender.
       */
      @java.lang.Override
      public int getGender() {
        return gender_;
      }
      /**
       * <code>int32 gender = 2;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(int value) {

        gender_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gender = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList keywords_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureKeywordsIsMutable() {
        if (!keywords_.isModifiable()) {
          keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @return A list containing the keywords.
       */
      public com.google.protobuf.ProtocolStringList
          getKeywordsList() {
        keywords_.makeImmutable();
        return keywords_;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @return The count of keywords.
       */
      public int getKeywordsCount() {
        return keywords_.size();
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param index The index of the element to return.
       * @return The keywords at the given index.
       */
      public java.lang.String getKeywords(int index) {
        return keywords_.get(index);
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the keywords at the given index.
       */
      public com.google.protobuf.ByteString
          getKeywordsBytes(int index) {
        return keywords_.getByteString(index);
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param index The index to set the value at.
       * @param value The keywords to set.
       * @return This builder for chaining.
       */
      public Builder setKeywords(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureKeywordsIsMutable();
        keywords_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param value The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywords(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureKeywordsIsMutable();
        keywords_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param values The keywords to add.
       * @return This builder for chaining.
       */
      public Builder addAllKeywords(
          java.lang.Iterable<java.lang.String> values) {
        ensureKeywordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keywords_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeywords() {
        keywords_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keywords = 4;</code>
       * @param value The bytes of the keywords to add.
       * @return This builder for chaining.
       */
      public Builder addKeywordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureKeywordsIsMutable();
        keywords_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object ext_ = "";
      /**
       * <code>string ext = 5;</code>
       * @return The ext.
       */
      public java.lang.String getExt() {
        java.lang.Object ref = ext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ext = 5;</code>
       * @return The bytes for ext.
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        java.lang.Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ext = 5;</code>
       * @param value The ext to set.
       * @return This builder for chaining.
       */
      public Builder setExt(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ext_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string ext = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExt() {
        ext_ = getDefaultInstance().getExt();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string ext = 5;</code>
       * @param value The bytes for ext to set.
       * @return This builder for chaining.
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ext_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureTagsIsMutable() {
        if (!tags_.isModifiable()) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @return A list containing the tags.
       */
      public com.google.protobuf.ProtocolStringList
          getTagsList() {
        tags_.makeImmutable();
        return tags_;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @return The count of tags.
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param index The index of the element to return.
       * @return The tags at the given index.
       */
      public java.lang.String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the tags at the given index.
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param index The index to set the value at.
       * @param value The tags to set.
       * @return This builder for chaining.
       */
      public Builder setTags(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTagsIsMutable();
        tags_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param value The tags to add.
       * @return This builder for chaining.
       */
      public Builder addTags(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTagsIsMutable();
        tags_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param values The tags to add.
       * @return This builder for chaining.
       */
      public Builder addAllTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTags() {
        tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 6;</code>
       * @param value The bytes of the tags to add.
       * @return This builder for chaining.
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureTagsIsMutable();
        tags_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList category_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCategoryIsMutable() {
        if (!category_.isModifiable()) {
          category_ = new com.google.protobuf.LazyStringArrayList(category_);
        }
        bitField0_ |= 0x00000040;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @return A list containing the category.
       */
      public com.google.protobuf.ProtocolStringList
          getCategoryList() {
        category_.makeImmutable();
        return category_;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @return The count of category.
       */
      public int getCategoryCount() {
        return category_.size();
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param index The index of the element to return.
       * @return The category at the given index.
       */
      public java.lang.String getCategory(int index) {
        return category_.get(index);
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the category at the given index.
       */
      public com.google.protobuf.ByteString
          getCategoryBytes(int index) {
        return category_.getByteString(index);
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param index The index to set the value at.
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCategoryIsMutable();
        category_.set(index, value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param value The category to add.
       * @return This builder for chaining.
       */
      public Builder addCategory(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCategoryIsMutable();
        category_.add(value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param values The category to add.
       * @return This builder for chaining.
       */
      public Builder addAllCategory(
          java.lang.Iterable<java.lang.String> values) {
        ensureCategoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, category_);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        category_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 7;</code>
       * @param value The bytes of the category to add.
       * @return This builder for chaining.
       */
      public Builder addCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCategoryIsMutable();
        category_.add(value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList installedApps_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureInstalledAppsIsMutable() {
        if (!installedApps_.isModifiable()) {
          installedApps_ = new com.google.protobuf.LazyStringArrayList(installedApps_);
        }
        bitField0_ |= 0x00000080;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @return A list containing the installedApps.
       */
      public com.google.protobuf.ProtocolStringList
          getInstalledAppsList() {
        installedApps_.makeImmutable();
        return installedApps_;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @return The count of installedApps.
       */
      public int getInstalledAppsCount() {
        return installedApps_.size();
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param index The index of the element to return.
       * @return The installedApps at the given index.
       */
      public java.lang.String getInstalledApps(int index) {
        return installedApps_.get(index);
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param index The index of the value to return.
       * @return The bytes of the installedApps at the given index.
       */
      public com.google.protobuf.ByteString
          getInstalledAppsBytes(int index) {
        return installedApps_.getByteString(index);
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param index The index to set the value at.
       * @param value The installedApps to set.
       * @return This builder for chaining.
       */
      public Builder setInstalledApps(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInstalledAppsIsMutable();
        installedApps_.set(index, value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param value The installedApps to add.
       * @return This builder for chaining.
       */
      public Builder addInstalledApps(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInstalledAppsIsMutable();
        installedApps_.add(value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param values The installedApps to add.
       * @return This builder for chaining.
       */
      public Builder addAllInstalledApps(
          java.lang.Iterable<java.lang.String> values) {
        ensureInstalledAppsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, installedApps_);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstalledApps() {
        installedApps_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string installed_apps = 8;</code>
       * @param value The bytes of the installedApps to add.
       * @return This builder for chaining.
       */
      public Builder addInstalledAppsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureInstalledAppsIsMutable();
        installedApps_.add(value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UbixUser)
    }

    // @@protoc_insertion_point(class_scope:UbixUser)
    private static final com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser();
    }

    public static com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UbixUser>
        PARSER = new com.google.protobuf.AbstractParser<UbixUser>() {
      @java.lang.Override
      public UbixUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UbixUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UbixUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.atguigu.springcloud.other.proto.UbixUserModel.UbixUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UbixUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UbixUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/UbixUser.proto\"\213\001\n\010UbixUser\022\013\n\003u" +
      "id\030\001 \001(\t\022\016\n\006gender\030\002 \001(\005\022\013\n\003age\030\003 \001(\005\022\020\n" +
      "\010keywords\030\004 \003(\t\022\013\n\003ext\030\005 \001(\t\022\014\n\004tags\030\006 \003" +
      "(\t\022\020\n\010category\030\007 \003(\t\022\026\n\016installed_apps\030\010" +
      " \003(\tB4\n#com.atguigu.springcloud.other.pr" +
      "otoB\rUbixUserModelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UbixUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UbixUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UbixUser_descriptor,
        new java.lang.String[] { "Uid", "Gender", "Age", "Keywords", "Ext", "Tags", "Category", "InstalledApps", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
